var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc(0,undefined);
subject.inc('-1','undefined');
subject.inc('1','undefined');
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.normalize('212-XXX-XXXX');
subject.normalize('853-889-0795');
subject.format('159-409-3548','###.###.#### x###',{normalize:true});
subject.blackListNumber('212-XXX-XXXX');
subject.blackListNumber('674-235-9980');
